name: Scala Steward

on:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at 00:00 UTC (8 AM Philippine Time, UTC+8)
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
